name: CI
on:
  push:
    branches: ["*"]
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix build .
